export enum JobSnapshotChangeDetail {
    CREATION = 'CREATION',
    EXPIRE_DATE_CHANGE = 'EXPIRE_DATE_CHANGE',
    DESCRIPTION_CHANGE = 'DESCRIPTION_CHANGE',
    NEW_FILE = 'NEW_FILE',
    MORE_INFORMATION = 'MORE_INFORMATION',
    STATUS_CHANGE = 'STATUS_CHANGE',
    COLABORATOR_CHANGE = 'COLABORATOR_CHANGE'
}