export enum ReportDataType {
    CLOSED_JOBS = 'CLOSED_JOBS',
    DONE_JOBS = 'DONE_JOBS',
    NEW_JOBS = 'NEW_JOBS',
    APPROVED_JOBS = 'APPROVED_JOBS',
    NEW_USERS = 'NEW_USERS',
    INACTIVATED_USERS = 'INACTIVATED_USERS'
}